{% set name = "gcc_impl" %}
{% set version = "7.3.0" %}
{% set chost = ctng_cpu_arch ~ "-" ~ ctng_vendor ~ "-linux-gnu-" %}

package:
  name: gcc_impl_{{ target_platform }}
  version: {{ version }}

source:
  - url: https://ftp.gnu.org/gnu/gcc/gcc-{{ version }}/gcc-{{ version }}.tar.gz
    folder: .

  - url: https://ftp.gnu.org/gnu/binutils/binutils-2.29.1.tar.bz2
    folder: binutils

  # Get the patches from crosstool-ng
  # Using https://github.com/crosstool-ng/crosstool-ng/pull/1268
  - url: https://github.com/isuruf/crosstool-ng/archive/a04d081901f5cd997b72b0b31646424fa4cb12ff.tar.gz
    folder: crosstool_ng

build:
  number: 0
  skip: True  # [not linux]
  detect_binary_files_with_prefix: False

requirements:
  build:
    #- gcc_bootstrap_{{ target_platform }}
    #- make
  host:
    - sysroot-{{ target_platform }}
    #- binutils
  run:
    - sysroot-{{ target_platform }}

about:
  home: https://www.gnu.org/software/binutils/
  license: GPL 3
  license_file:
    - COPYING
    - COPYING.LIB
    - COPYING3
    - COPYING3.LIB
  summary: A set of programming tools for creating and managing binary programs, object files, libraries, profile data, and assembly source code.

extra:
  recipe-maintainers:
    - frol
    - isuruf
